### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by faroit** [flipcoder/decadence#2]
@flipcoder Hi, didn't find a way to contact you, so I abused the issue tracker.
I just found this project and I wanted to let you know that its really great. Actually friends and I wrote a similar thing a few years ago for at a hackday. We needed a text based sequencer format so that we can use git to diff the patterns and use a push controller to checkout different versions of the song. The sequencer is [here](https://github.com/RocketScienceAbteilung/git-wig and here is a demo song that shows our quite simple [text format](https://github.com/RocketScienceAbteilung/gitty-jean). Textbeat seems to be quite more advanced. But maybe you like the idea of semantically meaningful diff between to patterns/parts of a track.

**Comment by flipcoder** [comment]
Thanks for the feedback and glad to hear of all the interest in this idea.   I'm sure there will be even more interest once I get some videos of it in action.

I agree with you on the importance of diffs.  I've been toying around with the idea of using embedded metadata to get context for resolving merges, potentially for collab/realtime merging.  I'm experimenting with it in another text-based format (non-music) project.  I'm convinced there's a way (using only addition of per-line metadata, which could be concealed by the text editor) to get realtime collab working that doesn't lock you into an editor, web app, or syncing host.  If I'm successful with that I could see it benefiting formats like textbeat.

My email is flipcoder@gmail.com if you want to chat more.
