### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by HansZoellner** [flipcoder/decadence#4]
Hi, I'm trying to install textbeat on my system and after running 
`sudo python setup.py install` and trying to launch textbeat, i get
`Traceback (most recent call last):
  File "/usr/bin/textbeat", line 11, in <module>
    load_entry_point('textbeat==0.1.0', 'console_scripts', 'textbeat')()
  File "/home/hans/.local/lib/python3.8/site-packages/textbeat/__main__.py", line 62, in main
    from . import support
  File "/home/hans/.local/lib/python3.8/site-packages/textbeat/support.py", line 20, in <module>
    import textbeat.plugins as tbp
ModuleNotFoundError: No module named 'textbeat.plugins'
`
Any ideas?

**Comment by flipcoder** [comment]
Thanks.  Looks like the installer is broken.  I'll try to fix this.  You should be able to run it in-place by using the txbt scripts in the main folder.

**Comment by flipcoder** [comment]
Yeah the setup file is missing the plugins folder.  I'll push the changes.

**Comment by flipcoder** [comment]
Try pulling the newest changes.  It looks like it's working on my end now.

https://github.com/flipcoder/textbeat/commit/974b567ce1c8ea9ce182a45bd746702deea147f6

**Comment by HansZoellner** [comment]
Fantastic, that's fixed!

**Comment by HansZoellner** [comment]
That's fixed, fantastic!
